# Generated by Django 4.2.18 on 2026-09-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='ALL', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('posts_collected', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(default='MANUAL_DASHBOARD', max_length=50)),
                ('log_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Lagos State 2027 Gubernatorial Election', max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2027)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('party', models.CharField(help_text='e.g. APC, PDP, LP, NNPP, ADC', max_length=100)),
                ('alias_keywords', models.TextField(default='', help_text="Comma-separated keywords or aliases for automatic entity recognition, e.g. 'GRV, Rhodes-Vivour, Gbadebo'")),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_color', models.CharField(default='#3B82F6', help_text='Hex color for charts & badges', max_length=20)),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='tracker.staterace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('X', 'X (formerly Twitter)'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube Comments'), ('News Comments', 'News Comment Section')], db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, help_text='Unique ID from source platform', max_length=200)),
                ('author_name', models.CharField(blank=True, default='Anonymous', max_length=150)),
                ('author_handle', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('sentiment_label', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], db_index=True, max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Compound polarity score: -1.0 (very negative) to +1.0 (very positive)')),
                ('pos_score', models.FloatField(default=0.0)),
                ('neu_score', models.FloatField(default=0.0)),
                ('neg_score', models.FloatField(default=0.0)),
                ('sentiment_engine', models.CharField(default='VADER', help_text='Model used: VADER or Transformers/BERT', max_length=50)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tracker.candidate')),
                ('state_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tracker.staterace')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['platform', 'sentiment_label'], name='tracker_soc_platfor_a67143_idx'), models.Index(fields=['candidate', 'sentiment_label'], name='tracker_soc_candida_cf90dd_idx'), models.Index(fields=['published_at', 'sentiment_label'], name='tracker_soc_publish_f27de8_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
